<!-- START of: finna - RecordDriver/DefaultRecord/record-models.phtml -->
<?php $modelScripts = $this->partial('Helpers/modeljs-urls.phtml'); ?>
<div class="model-details">
    <div id="inline-viewer"></div>
    <strong>3D Mallit</strong>
    <ul>
    <?php
        $settings = $this->driver->getModelSettings();
        $settings['cubemap'] = [
            'path' => $this->imageSrc()->getImagesDirectoryPath(),
            'images' => [
                'px.png', 'nx.png', 'py.png', 'ny.png', 'pz.png', 'nz.png'
            ]
        ];
        $recordId = $this->driver->getUniqueID();
    ?>
    <?php foreach($this->models as $index => $sub): ?>
        <?php foreach ($sub as $format => $model): ?>
            <?php
                $modelLoadData = [
                    'id' => $recordId,
                    'index' => $index,
                    'format' => $format
                ];
            ?>
            <a href="#" class="model-trigger" data-modelload="<?=htmlspecialchars(json_encode($modelLoadData ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>" data-scripts="<?=$this->escapeHtmlAttr($modelScripts);?>"><div class="iconlabel format-0physicalobject"></div><span>Näytä malli <?=$format?></span></a>
            <li></li>
        <?php endforeach; ?>
    <?php endforeach; ?>
    </ul>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-models.phtml -->