<?php
    $model = '/vufind/themes/finna2/images/models/juomahinkka_test01.glb';
    $thumbnail = '/vufind/Cover/Show?id=museumplusria.testi&amp;index=0&amp;size=large';
?>
<div class="3d-wrapper" style="display:none;">
    <div class="3d-canvas-wrapper">
    </div>
    <div class="3d-model-information">
        <ul>
            <li>Verts: 1123123</li>
            <li>Size: 1231241gb</li>
        </ul>
    </div>
</div>