<?php
    $options = [
        'thumbnail' => $this->model['preview_url'],
        'id' => $this->driver->getUniqueId(),
        'cubemap' => [
            'path' => $this->imageSrc()->getImagesDirectoryPath(),
            'images' => [
                'px.png', 'nx.png', 'py.png', 'ny.png', 'pz.png', 'nz.png'
            ]
        ]
    ];
    // We can load the model viewer related scripts here, so they are loaded only when needed
    // TODO! REMEMBER!
?>
<div class="model-wrapper" style="display:none;width:100%;">
    <div class="model-canvas-wrapper" style="position:relative;text-align:center;">
        <img class="model-thumbnail" src="<?= $options['thumbnail']?>" alt="thumbnail">
        <span class="viewer-state-info" style="position:absolute;top:50;">Katsele</span>
        <div class="viewer-options"> 
            <div class="viewer-controls">
                <button class="viewer-btn model-fullscreen" type="button"><i class="fa fa-fullscreen"></i> <span class="sr-only">Fullscreen</span></button>
                <button class="viewer-btn model-wireframe" type="button"><i class="fa fa-bars"></i> <span class="sr-only">Wireframe</span></button>
            </div>
            <div class="viewer-statistics">
                <div>
                <button class="viewer-btn" data-toggle="collapse" data-target="#model-stats">Mallin tietoja</button>
                <div id="model-stats" class="collapse">
                    <table class="table table-finna-record record-details">
                        <tbody>
                            <tr>
                                <th>Verteksit:</th>
                                <td class="model-vertices">999999999</td>
                            </tr>
                            <tr>
                                <th>Kolmiot:</th>
                                <td class="model-triangles">1234567</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                </div>
                <div>
                <button class="viewer-btn" data-toggle="collapse" data-target="#model-author">Tekijätiedot</button>
                <div id="model-author" class="collapse">
                    <table class="table table-finna-record record-details">
                        <tbody>
                            <tr>
                                <th>Tekijän nimi:</th>
                                <td class="model-vertices">Matti Meikäläinen</td>
                            </tr>
                            <tr>
                                <th>Vuosi:</th>
                                <td class="model-triangles">1989</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    finna.modelViewer.create('model-canvas-wrapper', <?=json_encode($options)?>);
</script>